<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue'
import {api} from '../api'
import {ElMessage,ElMessageBox,type UploadFile} from 'element-plus'
import {clampPage} from '../review-utils'

const courses=ref<any[]>([]),jobs=ref<any[]>([]),courseId=ref(''),selectedDoc=ref<any>(null),analysis=ref<any>(null),readiness=ref<any>(null)
const outlineMode=ref<'document'|'course'>('document'),nodes=ref<any[]>([]),relations=ref<any[]>([]),selectedNode=ref<any>(null),treeRef=ref<any>(null)
const previewUrl=ref(''),downloadUrl=ref(''),previewKind=ref('unavailable'),previewError=ref(''),previewText=ref(''),parserStatus=ref<any>(null)
const page=ref(1),pageInput=ref(1),file=ref<File|null>(null),uploading=ref(false);let timer:number|undefined
const fail=(e:any,m:string)=>ElMessage.error(e.response?.data?.detail||m)
const totalPages=computed(()=>Math.max(1,Number(selectedDoc.value?.total_pages||1)))
const pdfUrl=computed(()=>previewUrl.value?`${previewUrl.value}#page=${page.value}&view=FitH`:'')
const treeData=computed(()=>{const map=new Map(nodes.value.map(x=>[x.node_id,{...x,label:x.title,children:[]}])) as Map<string,any>;const roots:any[]=[];for(const item of map.values()){if(item.parent_id&&map.has(item.parent_id))map.get(item.parent_id).children.push(item);else roots.push(item)}return roots})
const sections=computed(()=>nodes.value.filter(x=>x.node_type==='section'))

async function load(){const[c,p]=await Promise.all([api.get('/teacher/courses'),api.get('/system/parser-status')]);courses.value=c.data;parserStatus.value=p.data;if(!courseId.value&&courses.value.length)courseId.value=courses.value[0].course_id;await loadJobs()}
async function loadJobs(){if(!courseId.value)return;const[j,r]=await Promise.all([api.get(`/teacher/courses/${courseId.value}/ingestion-jobs`),api.get(`/teacher/courses/${courseId.value}/publish-readiness`)]);jobs.value=j.data;readiness.value=r.data;if(selectedDoc.value)selectedDoc.value=jobs.value.find(x=>x.document_id===selectedDoc.value.document_id)||selectedDoc.value}
function choose(x:UploadFile){file.value=x.raw||null}
async function upload(){if(!file.value)return;const form=new FormData();form.append('file',file.value);uploading.value=true;try{await api.post(`/teacher/courses/${courseId.value}/documents`,form,{timeout:0});file.value=null;ElMessage.success('资料已进入解析与语义分析队列');await loadJobs()}catch(e){fail(e,'上传失败')}finally{uploading.value=false}}
async function applyPreview(data:any){previewUrl.value=data.preview_url;downloadUrl.value=data.download_url;previewKind.value=data.preview_kind;previewError.value=data.preview_error||'';previewText.value='';if(['text','markdown'].includes(previewKind.value)){const response=await fetch(previewUrl.value);if(!response.ok)throw new Error('文本预览加载失败');previewText.value=await response.text()}}
async function openDocument(job:any){selectedDoc.value=job;outlineMode.value='document';const[preview,latest]=await Promise.all([api.post(`/documents/${job.document_id}/preview-token`),api.get(`/teacher/documents/${job.document_id}/semantic-analysis/latest`)]);await applyPreview(preview.data);selectedDoc.value={...job,...preview.data};analysis.value=latest.data;page.value=pageInput.value=1;await loadOutline()}
async function loadOutline(){if(!courseId.value)return;try{const result=outlineMode.value==='document'&&selectedDoc.value?await api.get(`/teacher/documents/${selectedDoc.value.document_id}/outline`):await api.get(`/teacher/courses/${courseId.value}/outline`);nodes.value=result.data.nodes;relations.value=result.data.relations;selectedNode.value=nodes.value.find(x=>x.node_type==='knowledge_point')||nodes.value[0]||null;if(selectedNode.value)await sourceForNode(selectedNode.value)}catch(e){fail(e,'目录加载失败')}}
async function sourceForNode(node:any){selectedNode.value=node;const source=node.sources?.[0];if(!source)return;if(source.document_id!==selectedDoc.value?.document_id){const job=jobs.value.find(x=>x.document_id===source.document_id);const preview=(await api.post(`/documents/${source.document_id}/preview-token`)).data;if(job)selectedDoc.value={...job,...preview};await applyPreview(preview)}page.value=pageInput.value=clampPage(source.page_number,totalPages.value,1)}
async function analyze(job:any){try{analysis.value=(await api.post(`/teacher/documents/${job.document_id}/semantic-analysis`)).data;ElMessage.success('完整语义分析已进入队列');await loadJobs()}catch(e){fail(e,'启动分析失败')}}
async function analysisAction(action:'retry'|'cancel'){if(!analysis.value)return;try{analysis.value=(await api.post(`/teacher/analysis-jobs/${analysis.value.analysis_job_id}/${action}`)).data}catch(e){fail(e,'任务操作失败')}}
async function saveNode(status?:string){if(!selectedNode.value)return;try{const body={title:selectedNode.value.title,markdown:selectedNode.value.markdown,keywords:selectedNode.value.keywords,parent_id:selectedNode.value.parent_id,sort_order:selectedNode.value.sort_order,status:status||selectedNode.value.status};await api.patch(`/teacher/knowledge-nodes/${selectedNode.value.node_id}`,body);ElMessage.success(status==='rejected'?'内容已驳回并移出目录':'知识节点已更新');await Promise.all([loadOutline(),loadJobs()])}catch(e){fail(e,'保存失败')}}
async function approveSection(){if(!selectedNode.value)return;const section=selectedNode.value.node_type==='section'?selectedNode.value:nodes.value.find(x=>x.node_id===selectedNode.value.parent_id);if(!section)return ElMessage.warning('请选择一个节或节内知识点');const targets=[section,...nodes.value.filter(x=>x.parent_id===section.node_id)];try{await Promise.all(targets.map(x=>api.patch(`/teacher/knowledge-nodes/${x.node_id}`,{status:'approved'})));ElMessage.success('本节知识点已批准');await Promise.all([loadOutline(),loadJobs()])}catch(e){fail(e,'批量批准失败')}}
async function mergeChecked(){const ids=(treeRef.value?.getCheckedKeys()||[]).filter((id:string)=>nodes.value.find(x=>x.node_id===id)?.node_type==='knowledge_point');if(ids.length<2)return ElMessage.warning('请勾选至少两个知识点');const{value}=await ElMessageBox.prompt('合并后的知识点标题','合并知识点',{inputValue:nodes.value.find(x=>x.node_id===ids[0])?.title});await api.post('/teacher/knowledge-nodes/merge',{node_ids:ids,title:value});await loadOutline()}
async function splitSelected(){const x=selectedNode.value;if(!x||x.node_type!=='knowledge_point')return ElMessage.warning('请选择知识点');const text=x.markdown||'',middle=Math.max(1,Math.floor(text.length/2));await api.post('/teacher/knowledge-nodes/split',{node_id:x.node_id,parts:[{title:`${x.title}（一）`,markdown:text.slice(0,middle)},{title:`${x.title}（二）`,markdown:text.slice(middle)}]});await loadOutline()}
async function reviewRelation(r:any,status:string){await api.patch(`/teacher/courses/${courseId.value}/knowledge-relations`,{relation_id:r.relation_id,status});await loadOutline()}
async function publish(){try{const x=(await api.post(`/teacher/courses/${courseId.value}/knowledge-versions/publish`)).data;ElMessage.success(`结构化知识库 v${x.version_number} 已发布`);await loadJobs()}catch(e){fail(e,'发布失败')}}
function go(v:any=pageInput.value){page.value=pageInput.value=clampPage(v,totalPages.value,page.value)}
onMounted(async()=>{await load();timer=window.setInterval(async()=>{await loadJobs();if(analysis.value&&['queued','running','retry_wait'].includes(analysis.value.status)){analysis.value=(await api.get(`/teacher/analysis-jobs/${analysis.value.analysis_job_id}`)).data;if(analysis.value.status==='review_required')await loadOutline()}},4000)})
onUnmounted(()=>timer&&clearInterval(timer))
</script>

<template><main class="content knowledge-center">
  <div class="page-title"><span class="eyebrow">KNOWLEDGE CENTER</span><h1>知识中心</h1><p class="muted">完整 Markdown 经 AI 分批分析、证据校验和教师审核后发布。</p></div>
  <el-alert v-if="parserStatus" :type="parserStatus.mineru.status==='ok'?'success':'warning'" :closable="false"><template #title>远程解析：MinerU {{parserStatus.mineru.status}} · Pix2Text {{parserStatus.pix2text.status}} · 知识树 {{parserStatus.knowledge_extractor?.backend}}</template><span v-if="parserStatus.mineru.error">{{parserStatus.mineru.error}}</span><span v-if="parserStatus.knowledge_extractor?.warning">{{parserStatus.knowledge_extractor.warning}}</span></el-alert>
  <el-alert v-if="readiness&&!readiness.can_publish" class="readiness-alert" type="warning" :closable="false"><template #title>知识库尚未达到发布条件</template><span v-for="item in readiness.blockers" :key="item.code">{{item.message}}（{{item.count}}）　</span></el-alert>
  <el-card shadow="never"><el-row :gutter="14" align="middle"><el-col :span="7"><el-select v-model="courseId" @change="loadJobs"><el-option v-for="x in courses" :key="x.course_id" :label="x.course_name" :value="x.course_id"/></el-select></el-col><el-col :span="10"><el-upload :auto-upload="false" :limit="1" :on-change="choose"><el-button>选择 PDF / DOCX / PPTX / Markdown / TXT</el-button></el-upload></el-col><el-col :span="7"><el-button type="primary" :loading="uploading" :disabled="!file" @click="upload">上传并入库</el-button><el-button @click="loadJobs">刷新</el-button></el-col></el-row></el-card>
  <el-card shadow="never" class="job-card"><template #header><div class="card-header"><b>资料、解析与语义分析</b><el-button type="success" :disabled="!readiness?.can_publish" @click="publish">发布已批准知识</el-button></div></template><el-table :data="jobs"><el-table-column prop="original_name" label="资料" min-width="220"/><el-table-column prop="status" label="文档解析"/><el-table-column prop="analysis_status" label="AI语义分析"><template #default="s"><el-tag :type="s.row.analysis_status==='failed'?'danger':s.row.analysis_status==='review_required'?'warning':'info'">{{s.row.analysis_status||'旧资料未分析'}}</el-tag></template></el-table-column><el-table-column prop="total_pages" label="页数"/><el-table-column label="操作" min-width="210"><template #default="s"><el-button link @click="openDocument(s.row)">打开</el-button><el-button link type="primary" :disabled="!['ready','review_required'].includes(s.row.status)||['queued','running'].includes(s.row.analysis_status)" @click="analyze(s.row)">完整重新分析</el-button></template></el-table-column></el-table></el-card>
  <el-alert v-if="analysis" :type="analysis.status==='failed'?'error':'info'" :closable="false"><template #title>AI分析：{{analysis.status}} · 阶段 {{analysis.current_stage}} · {{analysis.current_batch}}/{{analysis.total_batches}} 批 · API {{analysis.api_calls}} 次</template><p v-if="analysis.error_message">{{analysis.error_message}}</p><el-button v-if="analysis.status==='failed'" @click="analysisAction('retry')">断点重试</el-button><el-button v-if="['queued','running','retry_wait'].includes(analysis.status)" @click="analysisAction('cancel')">取消</el-button></el-alert>
  <section v-if="selectedDoc" class="structured-review">
    <div class="outline-pane"><el-radio-group v-model="outlineMode" @change="loadOutline"><el-radio-button value="document">文档独立目录</el-radio-button><el-radio-button value="course">课程统一目录</el-radio-button></el-radio-group><div class="tree-actions"><el-button size="small" @click="mergeChecked">合并勾选知识点</el-button><el-button size="small" @click="splitSelected">拆分当前知识点</el-button></div><el-tree ref="treeRef" :data="treeData" node-key="node_id" show-checkbox default-expand-all highlight-current @node-click="sourceForNode"><template #default="{data}"><span>{{data.title}} <el-tag size="small">{{data.status}}</el-tag></span></template></el-tree></div>
    <div class="knowledge-editor"><template v-if="selectedNode"><div class="block-meta"><el-tag>{{selectedNode.node_type}}</el-tag><el-tag>{{selectedNode.status}}</el-tag></div><el-input v-model="selectedNode.title" placeholder="标题"/><el-input v-model="selectedNode.markdown" type="textarea" :autosize="{minRows:8,maxRows:24}" placeholder="知识点原文 Markdown"/><el-select v-if="selectedNode.node_type==='knowledge_point'" v-model="selectedNode.parent_id" placeholder="所属节"><el-option v-for="s in sections" :key="s.node_id" :label="s.title" :value="s.node_id"/></el-select><div class="block-actions"><el-button @click="saveNode()">保存</el-button><el-button type="success" @click="saveNode('approved')">批准</el-button><el-button type="danger" plain @click="saveNode('rejected')">驳回</el-button><el-button @click="approveSection">批准当前节</el-button></div></template><el-empty v-else description="分析完成后在左侧选择知识节点"/><el-divider>知识关系</el-divider><div v-for="r in relations" :key="r.relation_id" class="relation-row"><span>{{r.source_title}} — {{r.relation_type}} → {{r.target_title}}</span><el-tag>{{r.status}}</el-tag><el-button size="small" @click="reviewRelation(r,'approved')">确认</el-button><el-button size="small" @click="reviewRelation(r,'rejected')">驳回</el-button></div></div>
    <div class="source-review"><div class="page-selector"><el-button :disabled="page<=1" @click="go(page-1)">上一页</el-button><el-input-number v-model="pageInput" :controls="false" :min="1" :max="totalPages" @keyup.enter="go()"/><el-button @click="go()">跳转</el-button><strong>{{page}} / {{totalPages}}</strong><el-button :disabled="page>=totalPages" @click="go(page+1)">下一页</el-button><el-button tag="a" :href="downloadUrl" target="_blank">下载原文件</el-button></div><iframe v-if="previewKind==='pdf'&&pdfUrl" :key="pdfUrl" :src="pdfUrl" title="原文件对照"/><pre v-else-if="['text','markdown'].includes(previewKind)" class="text-preview">{{previewText}}</pre><el-result v-else icon="warning" title="预览不可用" :sub-title="previewError||'请下载原文件查看'"/></div>
  </section>
</main></template>
