<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api'
import KnowledgeGraphCanvas from '../components/KnowledgeGraphCanvas.vue'

type Row=Record<string,any>
const courses=ref<Row[]>([]),courseId=ref(''),data=ref<Row|null>(null),loading=ref(false),activeTab=ref('graph')
const search=ref(''),layout=ref<'force'|'circular'>('force'),relationKinds=ref<string[]>([])
const drawer=ref(false),selected=ref<Row|null>(null),selectedType=ref<'node'|'relation'>('node')
const importOpen=ref(false),importStep=ref(0),files=ref<File[]>([]),batch=ref<Row|null>(null),working=ref(false)
const syncRows=ref<Row[]>([])
const kindLabels:Row={part_of:'整体—部分',prerequisite:'前置关系',progression:'后续进阶',parallel:'双向并列',related:'相关'}
const fileKinds:Row={auto:'自动识别',nodes:'知识点清单',relations:'关系表',definitions:'关系定义',ignore:'忽略'}
const metrics=computed(()=>data.value?.metrics||{nodes:0,relations:0,approved:0,review_required:0,published_version:0})
const nodes=computed(()=>data.value?.nodes||[]),relations=computed(()=>data.value?.relations||[])
const reviewNodes=computed(()=>nodes.value.filter((x:Row)=>x.review_status==='draft'))
const reviewRelations=computed(()=>relations.value.filter((x:Row)=>x.review_status==='draft'))
const fail=(e:any,text:string)=>ElMessage.error(e?.response?.data?.detail||e?.message||text)
const tag=(value:string)=>value==='approved'?'success':value==='rejected'?'danger':'warning'

async function init(){try{courses.value=(await api.get('/teacher/courses')).data;if(courses.value.length){courseId.value=courses.value[0].course_id;await load()}}catch(e){fail(e,'知识图谱初始化失败')}}
async function load(){if(!courseId.value)return;loading.value=true;try{data.value=(await api.get(`/teacher/courses/${courseId.value}/knowledge-graph`)).data;syncRows.value=(await api.get(`/teacher/courses/${courseId.value}/knowledge-graph/source-diff`)).data}catch(e){fail(e,'知识图谱加载失败')}finally{loading.value=false}}
function selectNode(row:Row){selectedType.value='node';selected.value={...row};drawer.value=true}
function selectRelation(row:Row){selectedType.value='relation';selected.value={...row};drawer.value=true}
async function save(){if(!selected.value)return;try{const path=selectedType.value==='node'?`/teacher/knowledge-graph/nodes/${selected.value.graph_node_id}`:`/teacher/knowledge-graph/relations/${selected.value.graph_relation_id}`;await api.patch(path,selected.value);ElMessage.success('已保存审核结果');drawer.value=false;await load()}catch(e){fail(e,'保存失败')}}
function openImport(){files.value=[];batch.value=null;importStep.value=0;importOpen.value=true}
function chooseFiles(event:Event){files.value=Array.from((event.target as HTMLInputElement).files||[]).filter(file=>/\.xlsx?$/i.test(file.name))}
async function upload(){if(!files.value.length)return ElMessage.warning('请选择包含 XLS/XLSX 的文件夹');working.value=true;try{const created=(await api.post(`/teacher/courses/${courseId.value}/knowledge-graph/import-batches`,{batch_name:`图谱导入 ${new Date().toLocaleString()}`})).data;const id=created.batch_id;for(const file of files.value){const form=new FormData();form.append('file',file);form.append('relative_path',(file as any).webkitRelativePath||file.name);await api.post(`/teacher/knowledge-graph/import-batches/${id}/files`,form,{timeout:0})}batch.value=(await api.get(`/teacher/knowledge-graph/import-batches/${id}`)).data;importStep.value=2}catch(e){fail(e,'图谱文件夹上传失败')}finally{working.value=false}}
async function commit(){if(!batch.value)return;working.value=true;try{for(const file of batch.value.files)await api.patch(`/teacher/knowledge-graph/import-batches/${batch.value.batch_id}/files/${file.file_id}`,{kind:file.confirmed_kind});batch.value=(await api.post(`/teacher/knowledge-graph/import-batches/${batch.value.batch_id}/commit`,{},{timeout:0})).data;importStep.value=3;await load()}catch(e){fail(e,'图谱解析失败')}finally{working.value=false}}
async function importKnowledge(){try{const result=(await api.post(`/teacher/courses/${courseId.value}/knowledge-graph/import-approved-nodes`,{node_ids:[]})).data;ElMessage.success(`已导入 ${result.imported} 个已审核知识点`);await load()}catch(e){fail(e,'知识中心内容导入失败')}}
async function syncChanged(){const ids=syncRows.value.filter(x=>x.state==='changed').map(x=>x.graph_node_id);if(!ids.length)return ElMessage.info('没有需要同步的知识点');try{await api.post(`/teacher/courses/${courseId.value}/knowledge-graph/sync`,{graph_node_ids:ids});ElMessage.success(`已同步 ${ids.length} 个知识点到草稿`);await load()}catch(e){fail(e,'同步失败')}}
async function publish(){try{await ElMessageBox.confirm('发布后学生将看到新的不可变图谱版本，待审核节点和关系不会包含在内。','发布知识图谱',{type:'warning'});const result=(await api.post(`/teacher/courses/${courseId.value}/knowledge-graph/publish`)).data;ElMessage.success(`知识图谱 v${result.version_number} 已发布`);await load()}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e,'发布失败')}}
onMounted(init)
</script>

<template>
<main class="content graph-workbench" v-loading="loading">
  <header class="workbench-hero"><div><span>COURSE KNOWLEDGE GRAPH</span><h1>知识图谱</h1><p>独立建设、审核和发布课程关系网络，也可从知识中心导入已审核知识点快照。</p></div><div><el-button @click="importKnowledge">导入知识中心已审核内容</el-button><el-button type="primary" @click="openImport">整包导入图谱</el-button></div></header>
  <section class="workbench-filters"><el-select v-model="courseId" @change="load"><el-option v-for="course in courses" :key="course.course_id" :label="course.course_name" :value="course.course_id"/></el-select><el-input v-model="search" clearable placeholder="搜索知识点"/><el-select v-model="relationKinds" multiple collapse-tags clearable placeholder="筛选关系"><el-option v-for="(label,key) in kindLabels" :key="key" :label="label" :value="key"/></el-select><el-segmented v-model="layout" :options="[{label:'力导向',value:'force'},{label:'环形',value:'circular'}]"/><el-button @click="load">刷新</el-button></section>
  <section class="workbench-metrics"><article><span>图谱节点</span><strong>{{metrics.nodes}}</strong><small>{{metrics.approved}} 个已批准</small></article><article><span>知识关系</span><strong>{{metrics.relations}}</strong><small>明确关系与审核建议</small></article><article :class="{warn:metrics.review_required}"><span>待审核</span><strong>{{metrics.review_required}}</strong><small>不会进入学生版本</small></article><article><span>已发布版本</span><strong>v{{metrics.published_version}}</strong><small>{{syncRows.filter(x=>x.state==='changed').length}} 项可同步更新</small></article></section>
  <section class="graph-layout"><aside class="workbench-panel graph-side"><h2>图谱操作</h2><button :class="{active:activeTab==='graph'}" @click="activeTab='graph'">整体图谱 <b>{{metrics.nodes}}</b></button><button :class="{active:activeTab==='nodes'}" @click="activeTab='nodes'">节点审核 <b>{{reviewNodes.length}}</b></button><button :class="{active:activeTab==='relations'}" @click="activeTab='relations'">关系审核 <b>{{reviewRelations.length}}</b></button><button :class="{active:activeTab==='versions'}" @click="activeTab='versions'">发布版本 <b>{{data?.versions?.length||0}}</b></button><div class="side-actions"><el-button :disabled="!syncRows.some(x=>x.state==='changed')" @click="syncChanged">同步知识中心差异</el-button><el-button type="primary" @click="publish">发布给学生</el-button></div></aside>
    <section class="workbench-panel graph-main">
      <KnowledgeGraphCanvas v-if="activeTab==='graph'" :nodes="nodes" :relations="relations" :layout="layout" :search="search" :relation-kinds="relationKinds" @select-node="selectNode" @select-relation="selectRelation"/>
      <el-table v-else-if="activeTab==='nodes'" :data="nodes" height="650"><el-table-column prop="title" label="知识点" min-width="220"/><el-table-column label="属性" min-width="180"><template #default="s"><el-tag v-if="s.row.is_key" size="small">重点</el-tag><el-tag v-if="s.row.is_difficult" size="small" type="warning">难点</el-tag><el-tag v-if="s.row.is_exam" size="small" type="danger">考点</el-tag></template></el-table-column><el-table-column prop="origin" label="来源" width="140"/><el-table-column label="状态" width="110"><template #default="s"><el-tag :type="tag(s.row.review_status)">{{s.row.review_status}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button link @click="selectNode(s.row)">审核</el-button></template></el-table-column></el-table>
      <el-table v-else-if="activeTab==='relations'" :data="relations" height="650"><el-table-column prop="source_title" label="起点"/><el-table-column label="关系" width="130"><template #default="s">{{kindLabels[s.row.relation_kind]}}</template></el-table-column><el-table-column prop="target_title" label="终点"/><el-table-column prop="origin" label="来源" width="100"/><el-table-column label="状态" width="110"><template #default="s"><el-tag :type="tag(s.row.review_status)">{{s.row.review_status}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button link @click="selectRelation(s.row)">审核</el-button></template></el-table-column></el-table>
      <el-table v-else :data="data?.versions||[]"><el-table-column label="版本"><template #default="s">v{{s.row.version_number}}</template></el-table-column><el-table-column prop="node_count" label="节点"/><el-table-column prop="relation_count" label="关系"/><el-table-column prop="status" label="状态"/><el-table-column prop="published_at" label="发布时间"/></el-table>
    </section>
  </section>
  <el-drawer v-model="drawer" :title="selectedType==='node'?'审核图谱节点':'审核知识关系'" size="min(560px,96vw)"><template v-if="selected"><div class="drawer-form" v-if="selectedType==='node'"><el-input v-model="selected.title" placeholder="知识点名称"/><el-input v-model="selected.summary" type="textarea" :rows="3" placeholder="摘要"/><el-input v-model="selected.notes" type="textarea" :rows="4" placeholder="备注"/><div><el-checkbox v-model="selected.is_key">重点</el-checkbox><el-checkbox v-model="selected.is_difficult">难点</el-checkbox><el-checkbox v-model="selected.is_exam">考点</el-checkbox></div><el-radio-group v-model="selected.review_status"><el-radio-button value="approved">批准</el-radio-button><el-radio-button value="draft">待审核</el-radio-button><el-radio-button value="rejected">驳回</el-radio-button></el-radio-group></div><div class="drawer-form" v-else><p><b>{{selected.source_title}}</b> → <b>{{selected.target_title}}</b></p><el-select v-model="selected.relation_kind"><el-option v-for="(label,key) in kindLabels" :key="key" :label="label" :value="key"/></el-select><el-input v-model="selected.reason" type="textarea" :rows="5" placeholder="关系说明"/><el-radio-group v-model="selected.review_status"><el-radio-button value="approved">批准</el-radio-button><el-radio-button value="draft">待审核</el-radio-button><el-radio-button value="rejected">驳回</el-radio-button></el-radio-group></div></template><template #footer><el-button @click="drawer=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-drawer>
  <el-dialog v-model="importOpen" title="整包导入知识图谱" width="min(1080px,96vw)" :close-on-click-modal="false"><el-steps :active="importStep" finish-status="success"><el-step title="选择课程"/><el-step title="选择文件夹"/><el-step title="确认分类"/><el-step title="完成"/></el-steps><section v-if="importStep<2" class="graph-import"><label class="folder-drop"><input type="file" multiple webkitdirectory accept=".xls,.xlsx" @change="chooseFiles"/><b>选择知识图谱文件夹</b><span>支持知识点清单、知识关系和关系定义 Excel</span><em>{{files.length?`已选择 ${files.length} 个表格文件`:'尚未选择'}}</em></label></section><section v-else-if="importStep===2" class="graph-import"><div class="batch-progress"><span>待提交 {{batch?.files?.length||0}} 个文件</span><el-progress :percentage="0" :show-text="false"/></div><el-table :data="batch?.files||[]" height="460"><el-table-column prop="relative_path" label="目录 / 文件" min-width="300"/><el-table-column label="识别类型" width="180"><template #default="s"><el-select v-model="s.row.confirmed_kind"><el-option v-for="(label,key) in fileKinds" :key="key" :label="label" :value="key"/></el-select></template></el-table-column><el-table-column prop="stage" label="阶段" width="120"/><el-table-column label="进度" width="160"><template #default="s"><el-progress :percentage="s.row.progress" :show-text="false"/></template></el-table-column></el-table></section><section v-else class="import-done"><i>✓</i><h2>图谱导入完成</h2><p>识别 {{batch?.node_count||0}} 个清单知识点和 {{batch?.relation_count||0}} 条关系；异常端点已进入待审核。</p></section><template #footer><el-button @click="importOpen=false">{{importStep===3?'关闭':'取消'}}</el-button><el-button v-if="importStep<2" type="primary" :loading="working" @click="upload">上传并预分类</el-button><el-button v-else-if="importStep===2" type="primary" :loading="working" @click="commit">确认并生成图谱</el-button></template></el-dialog>
</main>
</template>

<style scoped>
.graph-workbench{display:grid;gap:17px;min-height:100vh;background:#f3f7f7}.graph-layout{display:grid;grid-template-columns:235px minmax(0,1fr);gap:15px}.graph-side{position:sticky;top:14px;display:grid;align-content:start;gap:7px;min-height:650px;padding:17px}.graph-side h2{margin:0 0 8px;color:#173e49}.graph-side>button{display:flex;justify-content:space-between;padding:12px;border:0;border-radius:9px;background:transparent;color:#61736f;text-align:left;cursor:pointer}.graph-side>button:hover,.graph-side>button.active{background:#edf7f4;color:#23746f}.graph-side b{color:#378f81}.side-actions{display:grid;gap:8px;margin-top:18px;padding-top:16px;border-top:1px solid #e3ece9}.graph-main{min-width:0;padding:16px}.drawer-form{display:grid;gap:14px}.folder-drop{display:grid;place-items:center;gap:8px;margin-top:25px;padding:52px;border:1.5px dashed #6da99f;border-radius:14px;background:#f2faf8;cursor:pointer}.folder-drop input{position:absolute;opacity:0;pointer-events:none}.folder-drop b{font-size:19px;color:#276f68}.folder-drop span{color:#718681}.folder-drop em{font-style:normal;color:#378f81}.batch-progress{display:grid;gap:8px;margin:24px 0 12px}.import-done{text-align:center;padding:50px}.import-done i{display:grid;place-items:center;width:70px;height:70px;margin:auto;border-radius:50%;background:#e2f5ee;color:#26816f;font-size:38px}@media(max-width:900px){.graph-layout{grid-template-columns:1fr}.graph-side{position:static;min-height:auto;grid-template-columns:repeat(2,1fr)}.graph-side h2,.side-actions{grid-column:1/-1}}
</style>
