<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, type UploadFile } from 'element-plus'
import { api } from '../api'
const courses=ref<any[]>([]),jobs=ref<any[]>([]),blocks=ref<any[]>([]),courseId=ref(''),file=ref<File|null>(null),health=ref<any>(null)
const fail=(e:any,m:string)=>ElMessage.error(e.response?.data?.detail||m)
async function load(){courses.value=(await api.get('/teacher/courses')).data;if(!courseId.value&&courses.value.length)courseId.value=courses.value[0].course_id;await loadJobs()}
async function loadJobs(){if(courseId.value){const [jobResult,healthResult]=await Promise.all([api.get(`/teacher/courses/${courseId.value}/ingestion-jobs`),api.get(`/teacher/courses/${courseId.value}/knowledge-health`)]);jobs.value=jobResult.data;health.value=healthResult.data}}
function choose(x:UploadFile){file.value=x.raw||null}
async function upload(){if(!file.value)return;const body=new FormData();body.append('file',file.value);try{await api.post(`/teacher/courses/${courseId.value}/documents`,body);file.value=null;ElMessage.success('资料已进入解析队列');await loadJobs()}catch(e){fail(e,'上传失败')}}
async function open(documentId:string){try{blocks.value=(await api.get(`/teacher/documents/${documentId}/blocks`)).data}catch(e){fail(e,'知识块加载失败')}}
async function review(block:any,accepted:boolean){try{const{data}=await api.patch(`/teacher/blocks/${block.block_id}/review`,{markdown:block.markdown,plain_text:block.plain_text,latex:block.latex,visibility_level:block.visibility_level,accepted});block.verification_status=data.verification_status;ElMessage.success(accepted?'已确认':'已驳回')}catch(e){fail(e,'审核失败')}}
async function publish(){try{const{data}=await api.post(`/teacher/courses/${courseId.value}/knowledge-versions/publish`);ElMessage.success(`知识版本 v${data.version_number} 已发布`)}catch(e){fail(e,'发布失败')}}
async function control(job:any,action:'cancel'|'retry'){try{await api.post(`/teacher/ingestion-jobs/${job.job_id}/${action}`);await loadJobs()}catch(e){fail(e,action==='cancel'?'取消失败':'重试失败')}}
onMounted(()=>load().catch(e=>fail(e,'页面加载失败')))
</script>
<template><main class="content"><el-page-header content="可信资料入库" @back="$router.push('/')"/><div class="page-title"><span class="eyebrow">KNOWLEDGE INGESTION</span><h1>课程知识库</h1><p class="muted">解析、审核并发布可追溯的课程资料。</p></div><el-row v-if="health" :gutter="12" class="health-row"><el-col v-for="item in [['总页数',health.total_pages],['原生页',health.native_pages],['OCR 页',health.ocr_pages],['公式',health.formula_count],['表格',health.table_count],['待审核',health.pending_regions],['失败页',health.failed_pages],['云端 Token',health.cloud_tokens]]" :key="item[0]" :span="3"><el-card shadow="never"><small>{{item[0]}}</small><strong>{{item[1]}}</strong></el-card></el-col></el-row><el-card shadow="never" class="toolbar-card"><el-row :gutter="16" align="middle"><el-col :span="7"><el-select v-model="courseId" placeholder="选择课程" @change="loadJobs"><el-option v-for="x in courses" :key="x.course_id" :label="x.course_name" :value="x.course_id"/></el-select></el-col><el-col :span="10"><el-upload :auto-upload="false" :limit="1" :on-change="choose"><el-button>选择资料</el-button></el-upload></el-col><el-col :span="7"><el-button type="primary" :disabled="!file" @click="upload">开始入库</el-button><el-button @click="loadJobs">刷新</el-button></el-col></el-row></el-card><el-card shadow="never"><template #header><div class="card-header"><b>解析任务</b><el-button type="success" @click="publish">发布已审核知识</el-button></div></template><el-table :data="jobs" empty-text="暂无任务"><el-table-column prop="original_name" label="资料"/><el-table-column prop="status" label="状态"/><el-table-column prop="progress" label="进度"/><el-table-column prop="total_pages" label="页数"/><el-table-column label="操作"><template #default="s"><el-button link type="primary" :disabled="s.row.status!=='review_required'" @click="open(s.row.document_id)">审核</el-button><el-button v-if="['queued','running'].includes(s.row.status)" link type="danger" @click="control(s.row,'cancel')">取消</el-button><el-button v-if="['failed','cancelled'].includes(s.row.status)" link type="warning" @click="control(s.row,'retry')">重试</el-button></template></el-table-column></el-table></el-card><el-card v-if="blocks.length" shadow="never" class="review-card"><template #header><b>知识块审核</b></template><div v-for="block in blocks" :key="block.block_id" class="block-review"><div class="block-meta"><el-tag>{{block.block_type}}</el-tag><span>第 {{block.page_number}} 页</span><el-tag :type="block.verification_status==='teacher_verified'?'success':'warning'">{{block.verification_status}}</el-tag></div><el-input v-model="block.plain_text" type="textarea" :rows="4"/><div class="block-actions"><el-select v-model="block.visibility_level"><el-option v-for="x in ['PUBLIC','GUIDANCE','ASSESSMENT','VAULT']" :key="x" :label="x" :value="x"/></el-select><el-button type="success" @click="review(block,true)">确认</el-button><el-button type="danger" plain @click="review(block,false)">驳回</el-button></div></div></el-card></main></template>
