<script setup lang="ts">
import {computed,nextTick,onMounted,onUnmounted,ref} from 'vue'
import {api} from '../api'
import {ElMessage,ElMessageBox,type UploadFile} from 'element-plus'
import {clampPage} from '../review-utils'
import MarkdownIt from 'markdown-it'
import {katex as katexPlugin} from '@mdit/plugin-katex'
import 'katex/dist/katex.min.css'

const courses=ref<any[]>([]),jobs=ref<any[]>([]),trash=ref<any[]>([]),courseId=ref(''),selectedDoc=ref<any>(null),analysis=ref<any>(null),readiness=ref<any>(null)
const outlineMode=ref<'document'|'course'>('document'),nodes=ref<any[]>([]),relations=ref<any[]>([]),selectedNode=ref<any>(null),treeRef=ref<any>(null)
const previewUrl=ref(''),downloadUrl=ref(''),previewKind=ref('unavailable'),previewError=ref(''),previewText=ref(''),parserStatus=ref<any>(null)
const page=ref(1),pageInput=ref(1),file=ref<File|null>(null),uploading=ref(false),analysisMode=ref<'api'|'local'>('api'),pptxHost=ref<HTMLElement|null>(null),selectedJobs=ref<any[]>([]),selectedTrash=ref<any[]>([]);let timer:number|undefined
const useOwnApi=ref(false),aiProvider=ref('openai_compatible'),aiBaseUrl=ref(''),aiModel=ref(''),aiApiKey=ref('')
const fail=(e:any,m:string)=>ElMessage.error(e.response?.data?.detail||m)
const totalPages=computed(()=>Math.max(1,Number(selectedDoc.value?.total_pages||1)))
const pdfUrl=computed(()=>previewUrl.value?`${previewUrl.value}#page=${page.value}&view=FitH`:'')
const treeData=computed(()=>{const map=new Map(nodes.value.map(x=>[x.node_id,{...x,label:x.title,children:[]}])) as Map<string,any>;const roots:any[]=[];for(const item of map.values()){if(item.parent_id&&map.has(item.parent_id))map.get(item.parent_id).children.push(item);else roots.push(item)}return roots})
const sections=computed(()=>nodes.value.filter(x=>x.node_type==='section'))
const markdown=new MarkdownIt({html:false,linkify:true,breaks:true}).use(katexPlugin,{delimiters:'all'})
const markdownHtml=computed(()=>markdown.render(previewText.value||''))
const selectedMarkdownHtml=computed(()=>markdown.render(selectedNode.value?.markdown||''))
const materialTypes=[
  ['syllabus','教学大纲'],['lesson_plan','教案'],['slides','课件'],
  ['textbook','教材'],['experiment','实验资料'],['question_bank','题库'],
  ['knowledge_graph','知识图谱'],['teaching_schedule','教学进度'],['other','其他']
]
const materialLabel=(value:string)=>materialTypes.find(x=>x[0]===value)?.[1]||'其他'
const parsePercent=(job:any)=>Math.max(0,Math.min(100,Number(job.progress||0)))
const analysisPercent=(job:any)=>{
  if(['review_required','completed'].includes(job.analysis_status))return 100
  const total=Number(job.analysis_total_batches||0),current=Number(job.analysis_current_batch||0)
  return total>0?Math.max(0,Math.min(99,Math.round(current*100/total))):0
}

async function load(){const[c,p]=await Promise.all([api.get('/teacher/courses'),api.get('/system/parser-status')]);courses.value=c.data;parserStatus.value=p.data;if(!courseId.value&&courses.value.length)courseId.value=courses.value[0].course_id;await loadJobs()}
async function loadJobs(){if(!courseId.value)return;const[j,r,t]=await Promise.all([api.get(`/teacher/courses/${courseId.value}/ingestion-jobs`),api.get(`/teacher/courses/${courseId.value}/publish-readiness`),api.get(`/teacher/courses/${courseId.value}/knowledge-trash`)]);jobs.value=j.data;readiness.value=r.data;trash.value=t.data;if(selectedDoc.value)selectedDoc.value=jobs.value.find(x=>x.document_id===selectedDoc.value.document_id)||selectedDoc.value}
async function changeCourse(){selectedDoc.value=null;selectedNode.value=null;analysis.value=null;nodes.value=[];relations.value=[];trash.value=[];previewUrl.value='';downloadUrl.value='';await loadJobs()}
function choose(x:UploadFile){file.value=x.raw||null}
async function upload(){if(!file.value)return;if(analysisMode.value==='api'&&useOwnApi.value&&(!aiBaseUrl.value||!aiModel.value||!aiApiKey.value))return ElMessage.warning('请完整填写自有 API 地址、模型和 API Key');const form=new FormData();form.append('file',file.value);form.append('analysis_mode',analysisMode.value);if(analysisMode.value==='api'&&useOwnApi.value){form.append('ai_provider',aiProvider.value);form.append('ai_base_url',aiBaseUrl.value);form.append('ai_model',aiModel.value);form.append('ai_api_key',aiApiKey.value)}uploading.value=true;try{await api.post(`/teacher/courses/${courseId.value}/documents`,form,{timeout:0});file.value=null;aiApiKey.value='';ElMessage.success(analysisMode.value==='api'?'资料已进入解析与 API 语义分析队列':'资料已进入解析与仅本地分析队列');await loadJobs()}catch(e){fail(e,'上传失败')}finally{uploading.value=false}}
async function applyPreview(data:any){previewUrl.value=data.preview_url;downloadUrl.value=data.download_url;previewKind.value=data.preview_kind;previewError.value=data.preview_error||'';previewText.value='';if(['text','markdown'].includes(previewKind.value)){const response=await fetch(previewUrl.value);if(!response.ok)throw new Error('文本预览加载失败');previewText.value=await response.text()}else if(previewKind.value==='pptx'){await nextTick();if(!pptxHost.value)throw new Error('PPTX 预览容器未准备好');pptxHost.value.innerHTML='';const response=await fetch(downloadUrl.value);if(!response.ok)throw new Error('PPTX 文件加载失败');const{init}=await import('pptx-preview');const renderer=init(pptxHost.value,{width:960,height:540,mode:'list'});await renderer.preview(await response.arrayBuffer())}}
async function openDocument(job:any){selectedDoc.value=job;outlineMode.value='document';const[preview,latest]=await Promise.all([api.post(`/documents/${job.document_id}/preview-token`),api.get(`/teacher/documents/${job.document_id}/semantic-analysis/latest`)]);await applyPreview(preview.data);selectedDoc.value={...job,...preview.data};analysis.value=latest.data;page.value=pageInput.value=1;await loadOutline()}
async function loadOutline(){if(!courseId.value)return;try{const result=outlineMode.value==='document'&&selectedDoc.value?await api.get(`/teacher/documents/${selectedDoc.value.document_id}/outline`):await api.get(`/teacher/courses/${courseId.value}/outline`);nodes.value=result.data.nodes;relations.value=result.data.relations;selectedNode.value=nodes.value.find(x=>x.node_type==='knowledge_point')||nodes.value[0]||null;if(selectedNode.value)await sourceForNode(selectedNode.value)}catch(e){fail(e,'目录加载失败')}}
async function sourceForNode(node:any){selectedNode.value=node;const source=node.sources?.[0];if(!source)return;if(source.document_id!==selectedDoc.value?.document_id){const job=jobs.value.find(x=>x.document_id===source.document_id);const preview=(await api.post(`/documents/${source.document_id}/preview-token`)).data;if(job)selectedDoc.value={...job,...preview};await applyPreview(preview)}page.value=pageInput.value=clampPage(source.page_number,totalPages.value,1)}
async function analyze(job:any){if(analysisMode.value==='api'&&useOwnApi.value&&(!aiBaseUrl.value||!aiModel.value||!aiApiKey.value))return ElMessage.warning('请完整填写自有 API 地址、模型和 API Key');const body:any={analysis_mode:analysisMode.value};if(analysisMode.value==='api'&&useOwnApi.value)Object.assign(body,{ai_provider:aiProvider.value,ai_base_url:aiBaseUrl.value,ai_model:aiModel.value,ai_api_key:aiApiKey.value});try{analysis.value=(await api.post(`/teacher/documents/${job.document_id}/semantic-analysis`,body)).data;aiApiKey.value='';ElMessage.success(analysisMode.value==='api'?'API 语义分析已进入队列':'仅本地分析已进入队列');await loadJobs()}catch(e){fail(e,'启动分析失败')}}
async function saveMaterial(job:any){try{await api.patch(`/teacher/documents/${job.document_id}/material-metadata`,{material_type:job.material_type,tags:job.tags||[]});ElMessage.success('资料用途与标签已确认');await loadJobs()}catch(e){fail(e,'资料分类保存失败')}}
async function deleteDocument(job:any){try{await ElMessageBox.confirm(`删除“${job.original_name}”及其未发布解析内容？此操作不可撤销。`,'删除错误资料',{type:'warning',confirmButtonText:'确认删除'});await api.delete(`/teacher/documents/${job.document_id}`);if(selectedDoc.value?.document_id===job.document_id){selectedDoc.value=null;selectedNode.value=null;nodes.value=[];previewUrl.value=''}ElMessage.success('错误资料及其解析内容已删除');await loadJobs()}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e,'删除资料失败')}}
async function deleteSelectedDocuments(){if(!selectedJobs.value.length)return ElMessage.warning('请先勾选资料');try{await ElMessageBox.confirm(`批量删除选中的 ${selectedJobs.value.length} 份资料及其未发布解析内容？`,'批量删除资料',{type:'warning'});const result=(await api.post('/teacher/documents/batch-delete',{ids:selectedJobs.value.map(x=>x.document_id)})).data;if(result.failed.length)ElMessage.warning(`已删除 ${result.deleted.length} 份，${result.failed.length} 份因运行中或已发布而保留`);else ElMessage.success(`已删除 ${result.deleted.length} 份资料`);if(result.deleted.includes(selectedDoc.value?.document_id)){selectedDoc.value=null;selectedNode.value=null;nodes.value=[];previewUrl.value=''}selectedJobs.value=[];await loadJobs()}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e,'批量删除资料失败')}}
async function analysisAction(action:'retry'|'cancel'){if(!analysis.value)return;try{analysis.value=(await api.post(`/teacher/analysis-jobs/${analysis.value.analysis_job_id}/${action}`)).data}catch(e){fail(e,'任务操作失败')}}
async function saveNode(status?:string){if(!selectedNode.value)return;try{const body={title:selectedNode.value.title,markdown:selectedNode.value.markdown,keywords:selectedNode.value.keywords,parent_id:selectedNode.value.parent_id,sort_order:selectedNode.value.sort_order,status:status||selectedNode.value.status};await api.patch(`/teacher/knowledge-nodes/${selectedNode.value.node_id}`,body);ElMessage.success(status==='rejected'?'内容已驳回并移出目录':'知识节点已更新');await Promise.all([loadOutline(),loadJobs()])}catch(e){fail(e,'保存失败')}}
async function rejectNode(){if(!selectedNode.value)return;try{const{value}=await ElMessageBox.prompt('请简要填写驳回原因，便于后续恢复和复核。','驳回知识点',{inputPlaceholder:'例如：超纲、重复、识别错误',inputValidator:v=>!!String(v||'').trim()||'请填写驳回原因'});await api.patch(`/teacher/knowledge-nodes/${selectedNode.value.node_id}`,{status:'rejected',reason:value});ElMessage.success('内容已移入独立回收站');await Promise.all([loadOutline(),loadJobs()])}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e,'驳回失败')}}
async function approveSection(){if(!selectedNode.value)return;const section=selectedNode.value.node_type==='section'?selectedNode.value:nodes.value.find(x=>x.node_id===selectedNode.value.parent_id);if(!section)return ElMessage.warning('请选择一个节或节内知识点');const targets=[section,...nodes.value.filter(x=>x.parent_id===section.node_id)];try{await Promise.all(targets.map(x=>api.patch(`/teacher/knowledge-nodes/${x.node_id}`,{status:'approved'})));ElMessage.success('本节知识点已批准');await Promise.all([loadOutline(),loadJobs()])}catch(e){fail(e,'批量批准失败')}}
async function mergeChecked(){const ids=(treeRef.value?.getCheckedKeys()||[]).filter((id:string)=>nodes.value.find(x=>x.node_id===id)?.node_type==='knowledge_point');if(ids.length<2)return ElMessage.warning('请勾选至少两个知识点');const{value}=await ElMessageBox.prompt('合并后的知识点标题','合并知识点',{inputValue:nodes.value.find(x=>x.node_id===ids[0])?.title});await api.post('/teacher/knowledge-nodes/merge',{node_ids:ids,title:value});await loadOutline()}
async function splitSelected(){const x=selectedNode.value;if(!x||x.node_type!=='knowledge_point')return ElMessage.warning('请选择知识点');const text=x.markdown||'',middle=Math.max(1,Math.floor(text.length/2));await api.post('/teacher/knowledge-nodes/split',{node_id:x.node_id,parts:[{title:`${x.title}（一）`,markdown:text.slice(0,middle)},{title:`${x.title}（二）`,markdown:text.slice(middle)}]});await loadOutline()}
async function reviewRelation(r:any,status:string){await api.patch(`/teacher/courses/${courseId.value}/knowledge-relations`,{relation_id:r.relation_id,status});await loadOutline()}
async function previewTrash(item:any){const source=item.sources?.[0];if(!source)return ElMessage.warning('该知识点没有可预览的原始来源');const job=jobs.value.find(x=>x.document_id===source.document_id);if(!job)return ElMessage.warning('原始资料已不存在');await openDocument(job);page.value=pageInput.value=clampPage(source.page_number,totalPages.value,1)}
async function restoreTrash(item:any){try{await api.post(`/teacher/knowledge-trash/${item.node_id}/restore`);ElMessage.success('知识点已恢复为待审核');await Promise.all([loadJobs(),loadOutline()])}catch(e){fail(e,'恢复失败')}}
async function deleteTrash(item:any){try{await ElMessageBox.confirm(`永久删除“${item.title}”？此操作不可撤销。`,'彻底删除知识点',{type:'warning'});await api.delete(`/teacher/knowledge-trash/${item.node_id}`);ElMessage.success('知识点已彻底删除');await loadJobs()}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e,'彻底删除失败')}}
async function deleteSelectedTrash(){if(!selectedTrash.value.length)return ElMessage.warning('请先勾选回收站知识点');try{await ElMessageBox.confirm(`永久删除选中的 ${selectedTrash.value.length} 个知识点？历史发布版本引用的内容会自动保留。`,'批量彻底删除',{type:'warning'});const result=(await api.post('/teacher/knowledge-trash/batch-delete',{ids:selectedTrash.value.map(x=>x.node_id)})).data;if(result.failed.length)ElMessage.warning(`已删除 ${result.deleted.length} 个节点，${result.failed.length} 项受发布版本保护`);else ElMessage.success(`已删除 ${result.deleted.length} 个知识节点`);selectedTrash.value=[];await loadJobs()}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e,'批量删除失败')}}
async function publish(){try{const x=(await api.post(`/teacher/courses/${courseId.value}/knowledge-versions/publish`)).data;ElMessage.success(`结构化知识库 v${x.version_number} 已发布`);await loadJobs()}catch(e){fail(e,'发布失败')}}
function go(v:any=pageInput.value){page.value=pageInput.value=clampPage(v,totalPages.value,page.value)}
onMounted(async()=>{await load();timer=window.setInterval(async()=>{await loadJobs();if(analysis.value&&['queued','running','retry_wait'].includes(analysis.value.status)){analysis.value=(await api.get(`/teacher/analysis-jobs/${analysis.value.analysis_job_id}`)).data;if(analysis.value.status==='review_required')await loadOutline()}},4000)})
onUnmounted(()=>timer&&clearInterval(timer))
</script>

<template><main class="content knowledge-center">
  <div class="page-title"><span class="eyebrow">KNOWLEDGE CENTER</span><h1>知识中心</h1><p class="muted">完整 Markdown 经可选 API 或本地规则分批整理、证据校验和教师审核后发布。</p></div>
  <el-card v-if="jobs.length" shadow="never" class="progress-board">
    <div v-for="job in jobs" :key="`progress-${job.job_id}`" class="progress-row">
      <strong>{{job.original_name}}</strong>
      <span>文档解析</span><el-progress :percentage="parsePercent(job)" :stroke-width="9"/>
      <span>{{job.analysis_mode==='local'?'本地知识分析':'API 知识分析'}}</span>
      <el-progress :percentage="analysisPercent(job)" :stroke-width="9"
                   :status="job.analysis_status==='failed'?'exception':job.analysis_status==='review_required'?'success':undefined"/>
    </div>
  </el-card>
  <el-alert v-if="parserStatus" :type="parserStatus.mineru.status==='ok'?'success':'warning'" :closable="false"><template #title>远程解析：MinerU {{parserStatus.mineru.status}} · Pix2Text {{parserStatus.pix2text.status}} · 知识树 {{parserStatus.knowledge_extractor?.backend}}</template><span v-if="parserStatus.mineru.error">{{parserStatus.mineru.error}}</span><span v-if="parserStatus.knowledge_extractor?.warning">{{parserStatus.knowledge_extractor.warning}}</span></el-alert>
  <el-alert v-if="readiness&&!readiness.can_publish" class="readiness-alert" type="warning" :closable="false"><template #title>知识库尚未达到发布条件</template><span v-for="item in readiness.blockers" :key="item.code">{{item.message}}（{{item.count}}）　</span></el-alert>
  <el-card shadow="never"><div class="analysis-choice"><b>知识整理方式</b><el-radio-group v-model="analysisMode"><el-radio-button value="api">允许调用 API（更智能）</el-radio-button><el-radio-button value="local">仅本地分析（不调用 API）</el-radio-button></el-radio-group><span class="muted">MinerU 与 Pix2Text 解析方式保持不变；这里仅控制后续知识点整理是否调用大模型。</span></div><div v-if="analysisMode==='api'" class="own-api-settings"><el-switch v-model="useOwnApi" active-text="使用教师自己的 API" inactive-text="使用服务器默认接口"/><template v-if="useOwnApi"><el-select v-model="aiProvider"><el-option label="OpenAI 兼容接口" value="openai_compatible"/><el-option label="Google Gemini" value="gemini"/></el-select><el-input v-model="aiBaseUrl" placeholder="Base URL，例如 https://api.example.com/v1"/><el-input v-model="aiModel" placeholder="模型名称"/><el-input v-model="aiApiKey" type="password" show-password autocomplete="off" placeholder="API Key"/></template><span class="muted">自有 Key 使用本机任务密钥加密，仅供后台 Worker 完成本次分析。</span></div><el-row :gutter="14" align="middle"><el-col :span="7"><el-select v-model="courseId" @change="changeCourse"><el-option v-for="x in courses" :key="x.course_id" :label="x.course_name" :value="x.course_id"/></el-select></el-col><el-col :span="10"><el-upload :auto-upload="false" :limit="1" :on-change="choose"><el-button>选择 PDF / DOCX / PPTX / Markdown / TXT</el-button></el-upload></el-col><el-col :span="7"><el-button type="primary" :loading="uploading" :disabled="!file" @click="upload">上传并入库</el-button><el-button @click="loadJobs">刷新</el-button></el-col></el-row></el-card>
  <el-card shadow="never" class="job-card"><template #header><div class="card-header"><div><b>资料、用途与语义分析</b><div class="muted">系统按内容建议用途，教师确认后用于课程知识组织；不会依赖文件路径或具体课程名称。</div></div><div><el-button type="danger" plain :disabled="!selectedJobs.length" @click="deleteSelectedDocuments">批量删除（{{selectedJobs.length}}）</el-button><el-button type="success" :disabled="!readiness?.can_publish" @click="publish">发布已批准知识</el-button></div></div></template><el-table :data="jobs" @selection-change="selectedJobs=$event"><el-table-column type="selection" width="46"/><el-table-column prop="original_name" label="资料" min-width="190"/><el-table-column label="资料用途" min-width="160"><template #default="s"><el-select v-model="s.row.material_type" size="small"><el-option v-for="item in materialTypes" :key="item[0]" :label="item[1]" :value="item[0]"/></el-select><small class="classification-hint">{{s.row.classification_status==='confirmed'?'教师已确认':`系统建议：${materialLabel(s.row.suggested_material_type)}`}}</small></template></el-table-column><el-table-column label="分类标签" min-width="190"><template #default="s"><el-select v-model="s.row.tags" multiple filterable allow-create default-first-option size="small" placeholder="输入标签并回车"/></template></el-table-column><el-table-column prop="status" label="文档解析" width="110"/><el-table-column prop="analysis_status" label="AI语义分析" width="125"><template #default="s"><el-tag :type="s.row.analysis_status==='failed'?'danger':s.row.analysis_status==='review_required'?'warning':'info'">{{s.row.analysis_status||'未分析'}}</el-tag></template></el-table-column><el-table-column label="操作" min-width="260" fixed="right"><template #default="s"><el-button link @click="openDocument(s.row)">预览/审核</el-button><el-button link type="success" @click="saveMaterial(s.row)">确认分类</el-button><el-button link type="primary" :disabled="!['ready','review_required'].includes(s.row.status)||['queued','running'].includes(s.row.analysis_status)" @click="analyze(s.row)">重新分析</el-button><el-button link type="danger" @click="deleteDocument(s.row)">删除</el-button></template></el-table-column></el-table></el-card>
  <el-card shadow="never" class="trash-card"><template #header><div class="card-header"><div><b>知识点回收站</b><span class="muted">审批不通过的内容与正式知识树隔离，可恢复或彻底删除。</span></div><div><el-button type="danger" plain :disabled="!selectedTrash.length" @click="deleteSelectedTrash">批量彻底删除（{{selectedTrash.length}}）</el-button><el-tag type="info">{{trash.length}} 项</el-tag></div></div></template><el-empty v-if="!trash.length" description="暂无被驳回的知识点"/><el-table v-else :data="trash" @selection-change="selectedTrash=$event"><el-table-column type="selection" width="46"/><el-table-column prop="title" label="知识点" min-width="220"/><el-table-column label="类型" width="110"><template #default="s"><el-tag>{{s.row.node_type}}</el-tag></template></el-table-column><el-table-column prop="reason" label="进入原因" min-width="180"/><el-table-column prop="original_name" label="来源资料" min-width="160"><template #default="s">{{s.row.original_name||s.row.sources?.[0]?.original_name||'课程统一知识树'}}</template></el-table-column><el-table-column prop="trashed_at" label="时间" width="165"/><el-table-column label="操作" width="220"><template #default="s"><el-button link @click="previewTrash(s.row)">预览来源</el-button><el-button link type="success" @click="restoreTrash(s.row)">恢复</el-button><el-button link type="danger" @click="deleteTrash(s.row)">彻底删除</el-button></template></el-table-column></el-table></el-card>
  <el-alert v-if="analysis" :type="analysis.status==='failed'?'error':analysis.warnings?.length?'warning':'info'" :closable="false"><template #title>AI分析：{{analysis.status}} · 阶段 {{analysis.current_stage}} · {{analysis.current_batch}}/{{analysis.total_batches}} 批 · API {{analysis.api_calls}} 次</template><p v-if="analysis.error_message">{{analysis.error_message}}</p><p v-for="warning in analysis.warnings||[]" :key="warning" class="analysis-warning">{{warning}}</p><el-button v-if="analysis.status==='failed'" @click="analysisAction('retry')">断点重试</el-button><el-button v-if="['queued','running','retry_wait'].includes(analysis.status)" @click="analysisAction('cancel')">取消</el-button></el-alert>
  <section v-if="selectedDoc" class="structured-review">
    <div class="outline-pane"><el-radio-group v-model="outlineMode" @change="loadOutline"><el-radio-button value="document">文档独立目录</el-radio-button><el-radio-button value="course">课程统一目录</el-radio-button></el-radio-group><div class="tree-actions"><el-button size="small" @click="mergeChecked">合并勾选知识点</el-button><el-button size="small" @click="splitSelected">拆分当前知识点</el-button></div><el-tree ref="treeRef" :data="treeData" node-key="node_id" show-checkbox default-expand-all highlight-current @node-click="sourceForNode"><template #default="{data}"><span>{{data.title}} <el-tag size="small">{{data.status}}</el-tag></span></template></el-tree></div>
    <div class="knowledge-editor"><template v-if="selectedNode"><div class="block-meta"><el-tag>{{selectedNode.node_type}}</el-tag><el-tag>{{selectedNode.status}}</el-tag></div><el-input v-model="selectedNode.title" placeholder="标题"/><el-input v-model="selectedNode.markdown" type="textarea" :autosize="{minRows:8,maxRows:24}" placeholder="知识点原文 Markdown"/><el-divider>Markdown / LaTeX 审批预览</el-divider><div class="rendered-markdown" v-html="selectedMarkdownHtml"/><el-select v-if="selectedNode.node_type==='knowledge_point'" v-model="selectedNode.parent_id" placeholder="所属节"><el-option v-for="s in sections" :key="s.node_id" :label="s.title" :value="s.node_id"/></el-select><div class="block-actions"><el-button @click="saveNode()">保存</el-button><el-button type="success" @click="saveNode('approved')">批准</el-button><el-button type="danger" plain @click="rejectNode">驳回</el-button><el-button @click="approveSection">批准当前节</el-button></div></template><el-empty v-else description="分析完成后在左侧选择知识节点"/><el-divider>知识关系</el-divider><div v-for="r in relations" :key="r.relation_id" class="relation-row"><span>{{r.source_title}} — {{r.relation_type}} → {{r.target_title}}</span><el-tag>{{r.status}}</el-tag><el-button size="small" @click="reviewRelation(r,'approved')">确认</el-button><el-button size="small" @click="reviewRelation(r,'rejected')">驳回</el-button></div></div>
    <div class="source-review"><div class="page-selector"><el-button v-if="previewKind!=='pptx'" :disabled="page<=1" @click="go(page-1)">上一页</el-button><el-input-number v-if="previewKind!=='pptx'" v-model="pageInput" :controls="false" :min="1" :max="totalPages" @keyup.enter="go()"/><el-button v-if="previewKind!=='pptx'" @click="go()">跳转</el-button><strong v-if="previewKind!=='pptx'">{{page}} / {{totalPages}}</strong><el-button v-if="previewKind!=='pptx'" :disabled="page>=totalPages" @click="go(page+1)">下一页</el-button><el-tag v-else type="success">浏览器内 PPTX 预览</el-tag><el-button tag="a" :href="downloadUrl" target="_blank">下载原文件</el-button></div><iframe v-if="previewKind==='pdf'&&pdfUrl" :key="pdfUrl" :src="pdfUrl" title="原文件对照"/><div v-else-if="previewKind==='pptx'" ref="pptxHost" class="pptx-preview-host"/><div v-else-if="previewKind==='markdown'" class="rendered-markdown source-markdown" v-html="markdownHtml"/><pre v-else-if="previewKind==='text'" class="text-preview">{{previewText}}</pre><el-result v-else icon="warning" title="预览不可用" :sub-title="previewError||'请下载原文件查看'"/></div>
  </section>
</main></template>

<style scoped>
.analysis-choice{display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin-bottom:16px}
.analysis-choice .muted{flex:1;min-width:280px}
.own-api-settings{display:grid;grid-template-columns:220px repeat(3,minmax(180px,1fr));gap:12px;align-items:center;margin:0 0 18px}
.own-api-settings .muted{grid-column:1/-1}
.progress-board{margin:16px 0}
.progress-row{display:grid;grid-template-columns:minmax(180px,1.4fr) 90px minmax(160px,1fr) 120px minmax(160px,1fr);align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid #edf0f5}
.progress-row:last-child{border-bottom:0}
.progress-row strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
@media(max-width:900px){.progress-row,.own-api-settings{grid-template-columns:1fr}.analysis-choice .muted{min-width:100%}}
</style>
