<script setup lang="ts">
import { onMounted, ref } from 'vue';import { ElMessage } from 'element-plus';import { api } from '../api'
import { parseStudentPaste } from '../review-utils'
const classes=ref<any[]>([]),drawer=ref(false),selected=ref<any>(null),text=ref(''),members=ref<any[]>([]),result=ref<any>(null),loading=ref(false),passwordConfig=ref<any>(null)
const passwordOpen=ref(false),passwordStudent=ref<any>(null),newPassword=ref(''),confirmPassword=ref(''),resetting=ref(false)
async function load(){const [classResult,configResult]=await Promise.all([api.get('/teacher/classes'),api.get('/system/student-import-config')]);classes.value=classResult.data;passwordConfig.value=configResult.data}
async function open(){if(!selected.value)return;if(!passwordConfig.value?.configured)ElMessage.error(`请先在 ${passwordConfig.value?.config_path||'server.env'} 配置学生初始密码`);else if(passwordConfig.value.security_level==='weak')ElMessage.warning('当前统一初始密码较弱；允许导入，但学生首次登录前存在冒用风险');drawer.value=true;result.value=null;members.value=(await api.get(`/teacher/classes/${selected.value.class_id}/members`)).data}
function parsed(){return parseStudentPaste(text.value)}
async function paste(){loading.value=true;try{result.value=(await api.post(`/teacher/classes/${selected.value.class_id}/members/import`,{students:parsed()})).data;members.value=result.value.members;text.value='';await load();ElMessage.success('名单处理完成')}catch(e:any){ElMessage.error(e.response?.data?.detail||'导入失败')}finally{loading.value=false}}
async function fileImport(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const form=new FormData();form.append('file',file);loading.value=true;try{result.value=(await api.post(`/teacher/classes/${selected.value.class_id}/members/import-file`,form)).data;members.value=result.value.members;await load();ElMessage.success('名单文件处理完成')}catch(e:any){ElMessage.error(e.response?.data?.detail||'文件导入失败')}finally{loading.value=false;input.value=''}}
function openPassword(row:any){passwordStudent.value=row;newPassword.value='';confirmPassword.value='';passwordOpen.value=true}
async function resetPassword(){if(newPassword.value.length<10)return ElMessage.warning('新密码至少需要 10 个字符');if(newPassword.value!==confirmPassword.value)return ElMessage.warning('两次输入的密码不一致');resetting.value=true;try{await api.post(`/teacher/classes/${selected.value.class_id}/members/${passwordStudent.value.user_id}/reset-password`,{new_password:newPassword.value});passwordOpen.value=false;members.value=(await api.get(`/teacher/classes/${selected.value.class_id}/members`)).data;ElMessage.success('学生密码已重置；其下次登录必须设置个人密码')}catch(e:any){ElMessage.error(e.response?.data?.detail||'密码重置失败')}finally{resetting.value=false}}
onMounted(()=>load().catch(()=>undefined))
</script>
<template>
  <section class="member-console workbench-panel"><div><span>学生与账号</span><b>教学班成员管理</b><small>导入名单、查看账号状态并重置学生密码</small></div><el-select v-model="selected" value-key="class_id" placeholder="选择教学班"><el-option v-for="row in classes" :key="row.class_id" :label="`${row.class_name}（${row.member_count}人）`" :value="row"/></el-select><el-button type="primary" :disabled="!selected" @click="open">打开成员工作台</el-button></section>
  <el-drawer v-model="drawer" size="min(860px,96vw)" :title="`${selected?.class_name||''} · 学生与账号`"><el-alert title="学生以学号登录；教师重置后，旧登录会失效，学生下次登录必须重新设置个人密码。" type="info" :closable="false"/><el-tabs><el-tab-pane label="粘贴名单"><p class="muted">每行一个学号，或“学号,姓名”“学号⇥姓名”，最多 5000 行。</p><el-input v-model="text" type="textarea" :rows="8" placeholder="20260001,张三&#10;20260002,李四"/><el-button class="member-import-button" type="primary" :loading="loading" :disabled="!text.trim()" @click="paste">导入名单</el-button></el-tab-pane><el-tab-pane label="CSV / XLSX"><p class="muted">必需列：学号/student_number；可选列：姓名/display_name。</p><label class="file-picker"><input type="file" accept=".csv,.xlsx" @change="fileImport"/>选择名单文件</label></el-tab-pane></el-tabs><el-descriptions v-if="result" class="import-summary" :column="5" border><el-descriptions-item v-for="(value,key) in result.summary" :key="key" :label="String(key)">{{value}}</el-descriptions-item></el-descriptions><el-table v-if="result" :data="result.results" max-height="230"><el-table-column prop="row" label="行" width="55"/><el-table-column prop="student_number" label="学号"/><el-table-column prop="display_name" label="姓名"/><el-table-column prop="status" label="结果"/><el-table-column prop="message" label="说明"/></el-table><h3>现有成员（{{members.length}}）</h3><el-table :data="members"><el-table-column prop="student_number" label="学号" min-width="130"/><el-table-column prop="display_name" label="姓名" min-width="120"/><el-table-column label="账号状态" width="130"><template #default="s"><el-tag :type="s.row.must_change_password?'warning':'success'">{{s.row.must_change_password?'待修改密码':'正常'}}</el-tag></template></el-table-column><el-table-column prop="status" label="成员状态" width="100"/><el-table-column label="操作" width="110"><template #default="s"><el-button link type="primary" @click="openPassword(s.row)">重置密码</el-button></template></el-table-column></el-table></el-drawer>
  <el-dialog v-model="passwordOpen" title="重置学生密码" width="min(520px,92vw)" append-to-body><el-alert type="warning" :closable="false" :title="`正在重置 ${passwordStudent?.display_name||passwordStudent?.student_number} 的密码；该学生现有登录会失效。`"/><el-form label-position="top"><el-form-item label="新临时密码"><el-input v-model="newPassword" type="password" show-password autocomplete="new-password"/></el-form-item><el-form-item label="再次确认"><el-input v-model="confirmPassword" type="password" show-password autocomplete="new-password" @keyup.enter="resetPassword"/></el-form-item></el-form><template #footer><el-button @click="passwordOpen=false">取消</el-button><el-button type="primary" :loading="resetting" :disabled="newPassword.length<10||newPassword!==confirmPassword" @click="resetPassword">确认重置</el-button></template></el-dialog>
</template>

<style scoped>.member-console{display:grid;grid-template-columns:minmax(240px,1fr) minmax(260px,380px) auto;gap:16px;align-items:center;margin-top:16px;padding:18px}.member-console>div{display:grid;gap:4px}.member-console span{font-size:11px;letter-spacing:.1em;color:#378f81}.member-console b{font-size:17px;color:#173e49}.member-console small{color:#71827d}@media(max-width:800px){.member-console{grid-template-columns:1fr}}</style>
