<script setup lang="ts">
import { onMounted, ref } from 'vue';import { ElMessage } from 'element-plus';import { api } from '../api'
import { parseStudentPaste } from '../review-utils'
const classes=ref<any[]>([]),drawer=ref(false),selected=ref<any>(null),text=ref(''),members=ref<any[]>([]),result=ref<any>(null),loading=ref(false),passwordConfig=ref<any>(null)
async function load(){const [classResult,configResult]=await Promise.all([api.get('/teacher/classes'),api.get('/system/student-import-config')]);classes.value=classResult.data;passwordConfig.value=configResult.data}
async function open(){if(!selected.value)return;if(!passwordConfig.value?.configured)ElMessage.error(`请先在 ${passwordConfig.value?.config_path||'server.env'} 配置学生初始密码`);else if(passwordConfig.value.security_level==='weak')ElMessage.warning('当前统一初始密码较弱；允许导入，但学生首次登录前存在冒用风险');drawer.value=true;result.value=null;members.value=(await api.get(`/teacher/classes/${selected.value.class_id}/members`)).data}
function parsed(){return parseStudentPaste(text.value)}
async function paste(){loading.value=true;try{result.value=(await api.post(`/teacher/classes/${selected.value.class_id}/members/import`,{students:parsed()})).data;members.value=result.value.members;text.value='';await load();ElMessage.success('名单处理完成')}catch(e:any){ElMessage.error(e.response?.data?.detail||'导入失败')}finally{loading.value=false}}
async function fileImport(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const form=new FormData();form.append('file',file);loading.value=true;try{result.value=(await api.post(`/teacher/classes/${selected.value.class_id}/members/import-file`,form)).data;members.value=result.value.members;await load();ElMessage.success('名单文件处理完成')}catch(e:any){ElMessage.error(e.response?.data?.detail||'文件导入失败')}finally{loading.value=false;input.value=''}}
onMounted(()=>load().catch(()=>undefined))
</script>
<template><div class="member-fab"><el-select v-model="selected" value-key="class_id" placeholder="选择教学班导入学生"><el-option v-for="row in classes" :key="row.class_id" :label="`${row.class_name}（${row.member_count}人）`" :value="row"/></el-select><el-button type="primary" :disabled="!selected" @click="open">成员管理</el-button></div><el-drawer v-model="drawer" size="680px" :title="`${selected?.class_name||''} · 成员管理`"><el-alert title="学生以学号登录，统一初始密码由部署环境配置，首次登录必须修改。" type="info" :closable="false"/><el-tabs><el-tab-pane label="粘贴名单"><p class="muted">每行一个学号，或“学号,姓名”“学号⇥姓名”，最多 5000 行。</p><el-input v-model="text" type="textarea" :rows="8" placeholder="20260001,张三&#10;20260002,李四"/><el-button class="member-import-button" type="primary" :loading="loading" :disabled="!text.trim()" @click="paste">导入名单</el-button></el-tab-pane><el-tab-pane label="CSV / XLSX"><p class="muted">必需列：学号/student_number；可选列：姓名/display_name。</p><label class="file-picker"><input type="file" accept=".csv,.xlsx" @change="fileImport"/>选择名单文件</label></el-tab-pane></el-tabs><el-descriptions v-if="result" class="import-summary" :column="5" border><el-descriptions-item v-for="(value,key) in result.summary" :key="key" :label="String(key)">{{value}}</el-descriptions-item></el-descriptions><el-table v-if="result" :data="result.results" max-height="230"><el-table-column prop="row" label="行" width="55"/><el-table-column prop="student_number" label="学号"/><el-table-column prop="display_name" label="姓名"/><el-table-column prop="status" label="结果"/><el-table-column prop="message" label="说明"/></el-table><h3>现有成员（{{members.length}}）</h3><el-table :data="members"><el-table-column prop="student_number" label="学号"/><el-table-column prop="display_name" label="姓名"/><el-table-column prop="status" label="状态"/></el-table></el-drawer></template>
