<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{api}from'../api';import MemberManager from'./MemberManager.vue'
const loading=ref(true),courses=ref<any[]>([]),terms=ref<any[]>([]),classes=ref<any[]>([])
const courseFilter=ref(''),termFilter=ref(''),search=ref(''),createOpen=ref(false),createType=ref<'course'|'term'|'class'>('class')
const courseForm=reactive({course_name:'',description:''})
const termForm=reactive({term_name:'',academic_year:'',teaching_period:''})
const classForm=reactive({course_id:'',term_id:'',class_name:'',class_variant:'',teaching_time_slot:'',campus:'',cohort_year:'',major:'',teaching_level:''})
const filteredClasses=computed(()=>classes.value.filter(row=>(!courseFilter.value||row.course_id===courseFilter.value)&&(!termFilter.value||row.term_id===termFilter.value)&&(!search.value||[row.course_name,row.class_name,row.class_variant,row.campus,row.major].join(' ').toLowerCase().includes(search.value.toLowerCase()))))
const studentCount=computed(()=>classes.value.reduce((sum,row)=>sum+Number(row.member_count||0),0))
async function load(){loading.value=true;try{[courses.value,terms.value,classes.value]=(await Promise.all([api.get('/teacher/courses'),api.get('/teacher/terms'),api.get('/teacher/classes')])).map(x=>x.data)}finally{loading.value=false}}
async function createCourse(){await api.post('/teacher/courses',courseForm);Object.assign(courseForm,{course_name:'',description:''});ElMessage.success('课程已创建');await load()}
async function createTerm(){await api.post('/teacher/terms',termForm);Object.assign(termForm,{term_name:'',academic_year:'',teaching_period:''});ElMessage.success('教学年度/时段已创建');await load()}
async function createClass(){await api.post('/teacher/classes',classForm);Object.assign(classForm,{course_id:'',term_id:'',class_name:'',class_variant:'',teaching_time_slot:'',campus:'',cohort_year:'',major:'',teaching_level:''});ElMessage.success('教学班已创建');await load()}
function startCreate(type:'course'|'term'|'class'){createType.value=type;createOpen.value=true}
async function create(){try{if(createType.value==='course'){await createCourse()}else if(createType.value==='term'){await createTerm()}else{await createClass()}createOpen.value=false}catch(e:any){ElMessage.error(e.response?.data?.detail||'创建失败')}}
onMounted(load)
</script>
<template><main class="content teaching-scope" v-loading="loading">
  <header class="workbench-hero"><div><h1>课程与教学班</h1><p>按课程、学年学期、校区和专业管理教学范围与学生账号。</p></div><div><el-button @click="startCreate('course')">新增课程</el-button><el-button @click="startCreate('term')">新增学年学期</el-button><el-button type="primary" @click="startCreate('class')">新增教学班</el-button></div></header>
  <section class="scope-metrics workbench-metrics"><article><span>共享课程</span><strong>{{courses.length}}</strong><small>教师维护的课程空间</small></article><article><span>学年学期</span><strong>{{terms.length}}</strong><small>可复用教学时段</small></article><article><span>教学班</span><strong>{{classes.length}}</strong><small>支持校区和自定义班型</small></article><article><span>在册学生</span><strong>{{studentCount}}</strong><small>按教学班授权</small></article></section>
  <section class="scope-filter workbench-filters"><el-select v-model="courseFilter" clearable placeholder="全部课程"><el-option v-for="x in courses" :key="x.course_id" :label="x.course_name" :value="x.course_id"/></el-select><el-select v-model="termFilter" clearable placeholder="全部学年学期"><el-option v-for="x in terms" :key="x.term_id" :label="`${x.academic_year||''} ${x.teaching_period||x.term_name}`" :value="x.term_id"/></el-select><el-input v-model="search" clearable placeholder="搜索教学班、校区、专业或班型"/><el-button @click="courseFilter='';termFilter='';search=''">清空筛选</el-button></section>
  <section class="scope-layout"><aside class="workbench-panel"><div class="panel-title"><b>课程目录</b><small>{{courses.length}} 门课程</small></div><button type="button" class="course-card" :class="{active:!courseFilter}" @click="courseFilter=''">全部课程 <b>{{classes.length}}</b></button><button v-for="course in courses" :key="course.course_id" type="button" class="course-card" :class="{active:courseFilter===course.course_id}" @click="courseFilter=course.course_id"><span>{{course.course_name}}</span><b>{{course.class_count||0}}</b><small>{{course.description||'暂无课程说明'}}</small></button></aside>
    <section class="class-panel workbench-panel"><div class="panel-title"><div><b>教学班实施矩阵</b><small>同一课程可按校区、专业、年级和自定义版本并行开班</small></div><el-tag type="success">{{filteredClasses.length}} 个结果</el-tag></div><el-table :data="filteredClasses" empty-text="当前筛选下没有教学班"><el-table-column prop="course_name" label="课程" min-width="150"/><el-table-column prop="term_name" label="学年学期" min-width="145"/><el-table-column label="教学班 / 版本" min-width="170"><template #default="s"><b>{{s.row.class_name}}</b><small class="cell-sub">{{s.row.class_variant||'通用班型'}}</small></template></el-table-column><el-table-column label="教学范围" min-width="210"><template #default="s"><span>{{[s.row.campus,s.row.cohort_year&&s.row.cohort_year+'级',s.row.major,s.row.teaching_level].filter(Boolean).join(' · ')||'未设置'}}</span><small class="cell-sub">{{s.row.teaching_time_slot||'未设置授课时间'}}</small></template></el-table-column><el-table-column label="学生" width="90"><template #default="s"><el-tag type="success">{{s.row.member_count||0}} 人</el-tag></template></el-table-column></el-table></section>
  </section><MemberManager/>
  <el-dialog v-model="createOpen" title="创建教学范围" width="min(720px,94vw)"><el-segmented v-model="createType" :options="[{label:'课程',value:'course'},{label:'学年学期',value:'term'},{label:'教学班',value:'class'}]" block/><el-form v-if="createType==='course'" label-position="top" class="create-form"><el-form-item label="课程名称"><el-input v-model="courseForm.course_name"/></el-form-item><el-form-item label="课程说明"><el-input v-model="courseForm.description" type="textarea" :rows="4"/></el-form-item></el-form><el-form v-else-if="createType==='term'" label-position="top" class="create-form form-grid"><el-form-item label="显示名称"><el-input v-model="termForm.term_name" placeholder="2026-2027 第一学期"/></el-form-item><el-form-item label="学年"><el-input v-model="termForm.academic_year" placeholder="2026-2027"/></el-form-item><el-form-item label="教学时段"><el-input v-model="termForm.teaching_period" placeholder="第一学期"/></el-form-item></el-form><el-form v-else label-position="top" class="create-form form-grid"><el-form-item label="课程"><el-select v-model="classForm.course_id"><el-option v-for="x in courses" :key="x.course_id" :label="x.course_name" :value="x.course_id"/></el-select></el-form-item><el-form-item label="学年学期"><el-select v-model="classForm.term_id"><el-option v-for="x in terms" :key="x.term_id" :label="`${x.academic_year||''} ${x.teaching_period||x.term_name}`" :value="x.term_id"/></el-select></el-form-item><el-form-item label="教学班名称"><el-input v-model="classForm.class_name" placeholder="仁24信管1"/></el-form-item><el-form-item label="自定义班型 / 版本"><el-input v-model="classForm.class_variant" placeholder="A班 / 本部强化版"/></el-form-item><el-form-item label="校区"><el-input v-model="classForm.campus" placeholder="本部 / 仁济"/></el-form-item><el-form-item label="入学年级"><el-input v-model="classForm.cohort_year" placeholder="2024"/></el-form-item><el-form-item label="专业"><el-input v-model="classForm.major"/></el-form-item><el-form-item label="教学层级"><el-input v-model="classForm.teaching_level" placeholder="可选，不限于难度"/></el-form-item><el-form-item label="具体授课时间"><el-input v-model="classForm.teaching_time_slot" placeholder="周一 1-2 节 / 第1-8周"/></el-form-item></el-form><template #footer><el-button @click="createOpen=false">取消</el-button><el-button type="primary" @click="create">确认创建</el-button></template></el-dialog>
</main></template>
<style scoped>.teaching-scope{display:grid;gap:17px;min-height:100vh;background:#f3f7f7}.scope-metrics{margin:0}.scope-filter{grid-template-columns:minmax(220px,1fr) minmax(220px,1fr) minmax(300px,1.4fr) auto}.scope-layout{display:grid;grid-template-columns:270px minmax(0,1fr);gap:15px;align-items:start}.scope-layout>aside,.class-panel{padding:18px}.panel-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:15px}.panel-title>div{display:grid;gap:4px}.panel-title small{color:#788a85}.course-card{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:5px 10px;width:100%;margin-bottom:8px;padding:13px;border:1px solid #dfe9e6;border-radius:11px;background:#fff;color:#31554f;text-align:left;cursor:pointer}.course-card:hover,.course-card.active{border-color:#79aaa4;background:#edf7f4;box-shadow:inset 3px 0 #23746f}.course-card span{font-weight:700}.course-card small{grid-column:1/-1;color:#81918d;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cell-sub{display:block;margin-top:4px;color:#7c8d88}.create-form{margin-top:22px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 15px}@media(max-width:900px){.scope-filter,.scope-layout{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}}</style>
