<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage}from'element-plus';import{api}from'../api';import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),loading=ref(true),courses=ref<any[]>([]),terms=ref<any[]>([]),classes=ref<any[]>([])
const courseForm=reactive({course_name:'',description:''}),termForm=reactive({term_name:''}),classForm=reactive({course_id:'',term_id:'',class_name:''})
const stats=computed(()=>({courses:courses.value.length,classes:classes.value.length,members:classes.value.reduce((n,x)=>n+x.member_count,0),documents:courses.value.reduce((n,x)=>n+x.document_count,0)}))
async function load(){loading.value=true;try{[courses.value,terms.value,classes.value]=(await Promise.all([api.get('/teacher/courses'),api.get('/teacher/terms'),api.get('/teacher/classes')])).map(x=>x.data)}catch(e:any){ElMessage.error(e.response?.data?.detail||'教师数据加载失败')}finally{loading.value=false}}
async function createCourse(){await api.post('/teacher/courses',courseForm);Object.assign(courseForm,{course_name:'',description:''});ElMessage.success('课程已创建');await load()}
async function createTerm(){await api.post('/teacher/terms',termForm);termForm.term_name='';ElMessage.success('学期已创建');await load()}
async function createClass(){await api.post('/teacher/classes',classForm);Object.assign(classForm,{course_id:'',term_id:'',class_name:''});ElMessage.success('教学班已创建');await load()}
async function logout(){await auth.logout();window.location.href='/login'}
onMounted(load)
</script>
<template><el-container class="app-shell"><el-aside width="248px" class="sidebar"><div class="logo">智教伴学<small>教师工作台</small></div><el-menu default-active="overview"><el-menu-item index="overview">工作台概览</el-menu-item><el-menu-item index="courses">课程与教学班</el-menu-item><el-menu-item index="knowledge" disabled>知识库入库（建设中）</el-menu-item></el-menu></el-aside><el-container><el-header class="topbar"><div><span class="muted">教学空间</span><strong>可信课程建设</strong></div><div>{{auth.user?.display_name||auth.user?.username}} <el-button text @click="logout">退出</el-button></div></el-header><el-main class="content" v-loading="loading"><div class="page-title"><span class="eyebrow">TEACHER WORKSPACE</span><h1>课程知识工作台</h1><p class="muted">建立课程—学期—教学班骨架，再发布可追溯知识。</p></div><section class="metric-grid"><el-card shadow="never"><span>共享课程</span><b>{{stats.courses}}</b></el-card><el-card shadow="never"><span>教学班</span><b>{{stats.classes}}</b></el-card><el-card shadow="never"><span>班级成员</span><b>{{stats.members}}</b></el-card><el-card shadow="never"><span>课程资料</span><b>{{stats.documents}}</b></el-card></section><el-row :gutter="20"><el-col :span="14"><el-card shadow="never"><template #header><b>课程与教学班</b></template><el-table :data="classes" empty-text="先创建课程、学期和教学班"><el-table-column prop="course_name" label="课程"/><el-table-column prop="class_name" label="教学班"/><el-table-column prop="term_name" label="学期"/><el-table-column prop="member_count" label="成员" width="80"/></el-table></el-card></el-col><el-col :span="10"><el-card shadow="never"><template #header><b>快速创建</b></template><el-tabs><el-tab-pane label="课程"><el-form label-position="top"><el-form-item label="课程名称"><el-input v-model="courseForm.course_name"/></el-form-item><el-form-item label="课程说明"><el-input v-model="courseForm.description" type="textarea"/></el-form-item><el-button type="primary" :disabled="!courseForm.course_name" @click="createCourse">创建课程</el-button></el-form></el-tab-pane><el-tab-pane label="学期"><el-form label-position="top"><el-form-item label="学期名称"><el-input v-model="termForm.term_name" placeholder="例如：2026 秋季学期"/></el-form-item><el-button type="primary" :disabled="!termForm.term_name" @click="createTerm">创建学期</el-button></el-form></el-tab-pane><el-tab-pane label="教学班"><el-form label-position="top"><el-form-item label="课程"><el-select v-model="classForm.course_id"><el-option v-for="x in courses" :key="x.course_id" :label="x.course_name" :value="x.course_id"/></el-select></el-form-item><el-form-item label="学期"><el-select v-model="classForm.term_id"><el-option v-for="x in terms" :key="x.term_id" :label="x.term_name" :value="x.term_id"/></el-select></el-form-item><el-form-item label="教学班名称"><el-input v-model="classForm.class_name"/></el-form-item><el-button type="primary" :disabled="!classForm.course_id||!classForm.term_id||!classForm.class_name" @click="createClass">创建教学班</el-button></el-form></el-tab-pane></el-tabs></el-card></el-col></el-row></el-main></el-container></el-container></template>
